[
  ./flake-module.nix
  ./development/java.nix
  ./development/python.nix
  ./development/rust.nix
  ./development/bevy.nix
  ./development/go.nix
  ./development/gradle.nix
  ./development/node
  ./development/minecraft/fabric.nix
  ./operations/morph.nix
  ./operations/nixops.nix
  ./operations/nixos-anywhere.nix
  ./operations/terranix.nix
]
